# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

call_parentheses = "NoSingleString"
column_width = 100
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
quote_style = "AutoPreferSingle"

[sort_requires]
enabled = true
